const germanTypes = {
  fire: { name: "Feuer", svg: "./../assets/img/fire.svg" },
  grass: { name: "grass", svg: "./../assets/img/grass.svg" },
  water: { name: "Wasser", svg: "./../assets/img/water.svg" },
  bug: { name: "Käfer", svg: "./../assets/img/bug.svg" },
  normal: { name: "Normal", svg: "./../assets/img/normal.svg" },
  poison: { name: "Gift", svg: "./../assets/img/poison.svg" },
  electric: { name: "Elektro", svg: "./../assets/img/electric.svg" },
  ground: { name: "Boden", svg: "./../assets/img/ground.svg" },
  fairy: { name: "Fee", svg: "./../assets/img/fairy.svg" },
  psychic: { name: "Psycho", svg: "./../assets/img/psychic.svg" },
  fighting: { name: "Kampf", svg: "./../assets/img/fighting.svg" },
  rock: { name: "Gestein", svg: "./../assets/img/rock.svg" },
  ice: { name: "Eis", svg: "./../assets/img/ice.svg" },
  dragon: { name: "Drache", svg: "./../assets/img/dragon.svg" },
  dark: { name: "Unlicht", svg: "./../assets/img/dark.svg" },
  ghost: { name: "Geist", svg: "./../assets/img/ghost.svg" },
  steel: { name: "Stahl", svg: "./../assets/img/steel.svg" },
  flying: { name: "Flug", svg: "./../assets/img/flying.svg" },
};
