const Typesicons = {
  fire: { name: "Fire", svg: "./../pokedex/assets/img/fire.svg" },
  grass: { name: "Grass", svg: "./../pokedex/assets/img/grass.svg" },
  water: { name: "Water", svg: "./../pokedex/assets/img/water.svg" },
  bug: { name: "Bug", svg: "./../pokedex/assets/img/bug.svg" },
  normal: { name: "Normal", svg: "./../pokedex/assets/img/normal.svg" },
  poison: { name: "Poison", svg: "./../pokedex/assets/img/poison.svg" },
  electric: { name: "Electric", svg: "./../pokedex/assets/img/electric.svg" },
  ground: { name: "Ground", svg: "./../pokedex/assets/img/ground.svg" },
  fairy: { name: "Fairy", svg: "./../pokedex/assets/img/fairy.svg" },
  psychic: { name: "Psychic", svg: "./../pokedex/assets/img/psychic.svg" },
  fighting: { name: "Fighting", svg: "./../pokedex/assets/img/fighting.svg" },
  rock: { name: "Rock", svg: "./../pokedex/assets/img/rock.svg" },
  ice: { name: "Ice", svg: "./../pokedex/assets/img/ice.svg" },
  dragon: { name: "Dragon", svg: "./../pokedex/assets/img/dragon.svg" },
  dark: { name: "Dark", svg: "./../pokedex/assets/img/dark.svg" },
  ghost: { name: "Ghost", svg: "./../pokedex/assets/img/ghost.svg" },
  steel: { name: "Steel", svg: "./../pokedex/assets/img/steel.svg" },
  flying: { name: "Flying", svg: "./../pokedex/assets/img/flying.svg" },
};
